---
# Path to the Fluentd configuration directory.
fluentd_pos_files_dir: /var/lib/fuentd/pos-files

# Path to the oVirt engine.log file.
fluentd_ovirt_vdsm_log_pos_file: '{{ fluentd_pos_files_dir }}/ovirt-vdsm.log.pos'

# File mode for Fluentd configuration files.
fluentd_pos_files_mode: 0640

# File mode for Fluentd configuration directories.
fluentd_pos_files_dir_mode: 0750

# Sets oVirt vdsm.log collection
collect_ovirt_vdsm_log: false
