---
- name: Set basics facts
  set_fact:
    rsyslog_role_rules: "{{ rsyslog_basics_rules }}"

- name: Remove basics example config files from rsyslog.d
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: cleanup.yaml
