---
- name: Set basics facts
  set_fact:
    rsyslog_role_packages: "{{rsyslog_basics_packages | flatten | d([])}}"
    rsyslog_role_rules: "{{ rsyslog_basics_rules }}"

- name: Install/Update basics role packages and generate example configuration files to role subdir
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: deploy.yaml
