---
# Deploy configuration files
- name: Install/Update role packages and generate role configuration files to role subdir
  vars:
    __rsyslog_packages: "{{ __rsyslog_ovirt_prereq_packages + __rsyslog_ovirt_packages }}"
    __rsyslog_rules: "{{ __rsyslog_ovirt_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname ~ '/rsyslog' }}"
    tasks_from: deploy.yml

- name: Allow rsyslog to listen on collectd port
  seport:
    ports: "{{ rsyslog_read_collectd_port | d(44514) }}"
    proto: tcp
    setype: syslogd_port_t
    state: present
  when: 'ansible_selinux.mode in ["enforcing", "permissive"]'
  notify: restart rsyslogd
