---
- name: Validate fluentd_output_plugin parameter
  fail:
    msg: "'{{ fluentd_output_plugin }}' must be set to either 'elasticsearch' or 'fluentd'."
  when:
    - fluentd_output_plugin != fluentd_output_plugin_elasticsearch
    - fluentd_output_plugin != fluentd_output_plugin_fluentd
    - fluentd_output_plugin != fluentd_output_plugin_file

- name: Remove elasticsearch output plugin configuration
  file:
    state: absent
    path: '{{ fluentd_config_parts_dir }}/30-elasticsearch-output.conf'
  when: fluentd_output_plugin != fluentd_output_plugin_elasticsearch
  notify: restart fluentd

- name: Remove secure_forward output plugin configuration
  file:
    state: absent
    path: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'
  when: fluentd_output_plugin != fluentd_output_plugin_fluentd
  notify: restart fluentd

- name: Remove file output plugin configuration
  file:
    state: absent
    path: '{{ fluentd_config_parts_dir }}/30-file-output.conf'
  when: fluentd_output_plugin != fluentd_output_plugin_file
  notify: restart fluentd

- name: Set fluentd_fluentd_port fact (non-ssl)
  set_fact:
    fluentd_fluentd_port: 24224
  when:
    - not fluentd_use_ssl
    - not fluentd_fluentd_port is defined
    - fluentd_output_plugin == fluentd_output_plugin_fluentd

- name: Set fluentd_port fact (ssl)
  set_fact:
    fluentd_fluentd_port: 24284
  when:
    - fluentd_use_ssl and not fluentd_fluentd_port is defined
    - fluentd_output_plugin == fluentd_output_plugin_fluentd

- name: Set fluentd_elasticsearch_port fact (ssl)
  set_fact:
    fluentd_elasticsearch_port: 9200
  when:
    - fluentd_use_ssl
    - not fluentd_elasticsearch_port is defined
    - fluentd_output_plugin == fluentd_output_plugin_elasticsearch

- name: Install non-ssl client
  template:
    src: forward_no_ssl.conf
    dest: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - not fluentd_use_ssl
    - fluentd_output_plugin == fluentd_output_plugin_fluentd
  notify: restart fluentd

- name: Install ssl client
  template:
    src: forward_ssl.conf
    dest: '{{ fluentd_config_parts_dir }}/30-source-forward.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - fluentd_use_ssl
    - fluentd_output_plugin == fluentd_output_plugin_fluentd
  notify: restart fluentd

- name: Install elasticsearch client configuration
  template:
    src: elasticsearch_output.conf
    dest: '{{ fluentd_config_parts_dir }}/30-elasticsearch-output.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - fluentd_use_ssl
    - fluentd_output_plugin == fluentd_output_plugin_elasticsearch
  notify: restart fluentd

- name: Create fluentd file output logs directory
  file:
    name: '{{ fluentd_file_output_dir }}'
    owner: '{{ fluentd_owner }}'
    state: directory
  when:
    - fluentd_output_plugin == fluentd_output_plugin_file

- name: Install README in file output logs directory
  template:
    src: file_output_README.md
    dest: '{{ fluentd_file_output_dir }}/README.md'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - fluentd_output_plugin == fluentd_output_plugin_file
  notify: restart fluentd

- name: Install file client configuration
  template:
    src: file_output.conf
    dest: '{{ fluentd_config_parts_dir }}/30-file-output.conf'
    owner: '{{ fluentd_owner }}'
    group: '{{ fluentd_group }}'
    mode: '{{ fluentd_config_mode }}'
  when:
    - fluentd_output_plugin == fluentd_output_plugin_file
  notify: restart fluentd
