---
- name: Set debops facts
  set_fact:
    rsyslog_role_packages: ""
    rsyslog_role_rules: "{{ rsyslog_debops_rules }}"

- name: Install/Update debops role packages and generate example configuration files to role subdir
  include_role:
    name: "{{ logging_role_path|d('logging') }}/roles/rsyslog"
    tasks_from: deploy.yaml
