---
# Deploy configuration files
- name: Install/Update basics input packages
  vars:
    __rsyslog_packages: "{{ __rsyslog_basics_packages }}"
    __rsyslog_rules: []
  include_tasks:
    file: deploy.yml

- name: Create basics input configuration files in /etc/rsyslog.d
  vars:
    __rsyslog_input_name: "{{ basics_item.name }}"
    __rsyslog_input_type: "{{ basics_item.type }}"
    __rsyslog_packages: []
    __rsyslog_rules:
      - name: "input-basics-{{ basics_item.name }}"
        type: input
        state: "{{ basics_item.state | d('present') }}"
        sections:
          - options: "{{ lookup('template', __rsyslog_input_basics) }}"
  include_tasks:
    file: deploy.yml
  loop: '{{ logging_inputs }}'
  loop_control:
    loop_var: basics_item
    extended: yes
  when:
    - basics_item.type | d() == 'basics'
    - ansible_loop.first
