---
# Deploy configuration files
- name: Install/Update role packages and generate role configuration files for output to local files
  vars:
    __rsyslog_packages: "{{ __rsyslog_files_output_packages }}"
    __rsyslog_rules: "{{ __rsyslog_files_output_rules }}"
  include_role:
    name: "{{ role_path | dirname | dirname | dirname ~ '/rsyslog' }}"
    tasks_from: deploy.yml
