---
- name: Set Viaq-k8s facts
  set_fact:
    rsyslog_role_rules: "{{ rsyslog_viaq_k8s_rules }}"

- name: Remove Viaq-k8s role config files from subdir
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: cleanup.yaml
