---
# Deploy configuration files
- name: Remove Viaq-k8s role config files from subdir
  vars:
    __rsyslog_rules: "{{ __rsyslog_viaq_k8s_rules }}"
  include_role:
    name: "{{ role_path }}/../../../"
    tasks_from: cleanup.yaml
